name: capotcha
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.8

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # cupertino_icons: ^1.0.4
  intl: ^0.17.0
  shimmer: ^2.0.0
  url_launcher: ^6.0.20
  http: ^0.13.4
  provider: ^6.0.2
  cached_network_image: ^3.2.0
  carousel_slider: ^4.0.0
  # intro_slider:
  shared_preferences: ^2.0.13
  string_validator: ^0.3.0
  modal_progress_hud:
  flutter_verification_code: ^1.1.2+1
  flutter_svg: ^1.0.3
  fluttertoast: ^8.0.9
  flutter_counter: ^1.0.3
  awesome_dialog: ^2.2.0
  step_progress_indicator: ^1.0.2
  sqflite: ^2.0.2
  path_provider: ^2.0.9
  # path:
  font_awesome_flutter: ^10.1.0
  # circular_reveal_animation:
  flutter_staggered_animations:
  google_maps_flutter: ^2.1.3
  geolocator: ^8.2.0
  firebase_messaging: ^11.2.10
  firebase_core: ^1.13.1
  # geocoder:
  flutter_screenutil: ^5.3.1
  flutter_slidable: ^1.2.0
  google_fonts: ^2.3.1
  # device_preview:
  # octo_image:
  

  



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"


flutter:

  uses-material-design: true
  
  fonts:
   - family: CM Sans Serif
     fonts:
       - asset: assets/fonts/cm_sans_serif_2012.ttf
   - family: Cairo
     fonts:
       - asset: assets/fonts/Cairo-Regular.ttf
   - family: icon
     fonts:
       - asset: assets/fonts/icomoon.ttf

  assets:
      - assets/images/
      - assets/